### ISSUE TITLE
The dll in the nuget package does not have a strong name

### ISSUE THREAD

**Issue by Gensplejs** [RudeySH/EntityFramework.Utilities#10]
Yeah... what the title says. The dll in the nuget package does not have a strong name and that causes a compiler warning when using it from an assembly that has a strong name.
You also get a runtime error when trying to use it.
Exception;System.IO.FileLoadException: Could not load file or assembly 'RudeySH.EFUtilities, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by RudeySH** [comment]
I'm not familiar with strong names yet. Is the original EFUtilities strongly named? How can this be set up for an open source project?

**Comment by RudeySH** [comment]
Closed due to inactivity.
