### ISSUE TITLE
Performance tests have low code quality and are unfair

### ISSUE THREAD

**Issue by bartdebever** [RudeySH/EntityFramework.Utilities#14]
The performance tests within this respository are pretty unfair because there hasn't been looked at JIT optimalizations and the timing of the actions differs per implementation.

I will be working within a fork to fix these issues. Just wanted to make this issue to spread light on the issue and ask if this project is still active under your development.

**Comment by RudeySH** [comment]
Thanks for taking interest! I haven't worked on this project for a while but I am keeping an eye on issues and pull requests.

To be honest I have never looked at the performance tests in this project, they already existed in the original project of MikaelEliasson and I never changed them. That being said I'll happily accept any improvements.

**Comment by bartdebever** [comment]
I can already see that the code quality of the project isn't the most optimal, as I personally need this project pretty badly I will try to contribute more along the line.

The performance tests set up right now are pretty basic and can run within about 5 minutes. Issues with that being that they aren't complete at all. These tests only show us one roundtrip and not outliers or anything like that.
