### ISSUE TITLE
NullReferenceException when using private properties

### ISSUE THREAD

**Issue by Bouke** [RudeySH/EntityFramework.Utilities#17]
I'm implementing the embedded json strategy as detailed here: https://www.codeproject.com/Articles/1166099/Entity-Framework-Storing-complex-properties-as-JSO

When using DbContext's normal save operations, everything works fine. However when using `InsertAll`, it fails. After decompiling I've found that it tries to build the "accessors" and is trying to `[null].GetGetMethod(true)` for my internal (backing) field.

**Comment by RudeySH** [comment]
Hey! Can you provide a sample to reproduce this issue?

**Comment by RudeySH** [comment]
Closed due to inactivity.
