### ISSUE TITLE
Only Inserts Surface Entities, Nested Data is not Inserted?

### ISSUE THREAD

**Issue by aloksharma1** [RudeySH/EntityFramework.Utilities#20]
Hello,
for my need i want to do batch operations on nested entities like this:

`EFBatchOperation.For(db, db.ResortInfoes).InsertAll(resortsToInsert);`

where resorts entity have nested images, timetable & a bunch of other entities but the insert operation only pushed the surface data that is in `ResortInfoes `and ignored all `ICollection `related tables.

is this the correct behavior for this lib?

**Comment by RudeySH** [comment]
Yes, that is correct behavior for EFUtilities.

`InsertAll` offers improved performance, but has a couple of disadvantages, such as not being able to insert nested relationships.
