### ISSUE TITLE
UpdateAll => UpdateSpecification does not support the nested properties update or complex properties update

### ISSUE THREAD

**Issue by nazar-kuzo** [RudeySH/EntityFramework.Utilities#25]
Hey,

Thank you for your fork implementation of this library.

I have noticed that when you provide expressions to UpdateSpecification like:

x => x.Property.NestedProperty

it results into "NestedProperty" name provided by "GetPropertyName" extension
and fails matching with EF property mapping since there it is stored like "Property.NestedProperty".

as the sidenote, there is no way to update whole ComplexProperty as well because of that issue.

Could you please update "GetPropertyName" extension so it would work properly with nested properties?

**Comment by RudeySH** [comment]
How are you storing nested properties in SQL Server?

And can you elaborate on what you mean by "ComplexProperty", how does it relate to `x => x.Property.NestedProperty`?

**Comment by nazar-kuzo** [comment]
//Entity
public class Metric
    {
        [Key]
        public string Id { get; set; }

        //ComplexProperty via ComplexType
        public Reference Reference { get; set; }
    }

//ComplexType
[ComplexType]
    public class Reference
    {
        public string Id { get; set; }

        public string Name { get; set; }
    }

How EF handles it:
    [0]: NameOnObject = "Id" NameInDatabase = "Id"
    [8]: NameOnObject = "Reference.Id" NameInDatabase = "Reference_Id"
    [9]: NameOnObject = "Reference.Name" NameInDatabase = "Reference_Name"

**Comment by nazar-kuzo** [comment]
The use case scenario is that I want to update a property in Database which is a property of a Complex Type.

In this case I would expect to use expression like:
x => x.Reference.Name

**Comment by RudeySH** [comment]
I hadn't heard of about [ComplexType] before, and it sounds like the original author of EFUtilities hadn't either.

EFUtilities builds a mapping between classes and tables, and a mapping between properties and columns. As you have noted, it doesn't deal with `ComplexType` properly. I'll do some digging to see if there's a straightforward way to fix this.

**Comment by nazar-kuzo** [comment]
Here is a link to EF documentation about ComplexTypes
https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/data-types/complex-types

As the quick and dirty way to fix it I would suggest this:
add such lines of code to ExpressionHelper.GetPropertyName

40			var member = temp as MemberExpression;
41			return member?.Member.Name;

=>

            if (member?.Expression is MemberExpression parent)
            {
                return $"{parent.Member.Name}.{member?.Member.Name}";
            }
            else
            {
                return member?.Member.Name;
            }

it will look for parent MemberExpression and if it exisits - provide Parent.Child format

Anyway, thank you for a quick response.

**Comment by nazar-kuzo** [comment]
BTW,

my dirtly solution is rather workaround how to deal with ComplextType properties, and I would really appreciate if you could promote it soon.

Thanks again

**Comment by RudeySH** [comment]
I haven't gotten around to debugging the way the code currently works, but are you saying that if `GetPropertyName` returns a properly nested string like "Property.NestedProperty", it will be able to map that string to the proper column name? I'm worried the column mapping implementation won't contain the right property and column names, but I haven't checked it thoroughly yet.

**Comment by nazar-kuzo** [comment]
I haven't gotten around to debugging the way the code currently works, but are you saying that if GetPropertyName returns a properly nested string like "Property.NestedProperty", it will be able to map that string to the proper column name?
Yes, that is correct.

Right now I`m running your project locally and I can confirm that,
if you are bored due to quarantine and have couple of minutes for a screen share I`m ready 😂
my skype is nazar101095

**Comment by RudeySH** [comment]
I just published a new version to NuGet, 1.0.11. That should solve your issue.

I noticed an error will still pop up when the ComplexType property is set to `null`. I'm not sure if that's expected in EF6, though.
