### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by fhucko** [RudeySH/EntityFramework.Utilities#26]
Hello, are there any plans to support .NET standard? EF6 supports it since 6.3.

**Comment by fhucko** [comment]
I ended up copying bulk insert code into my own function, it is only few lines of code.

**Comment by RudeySH** [comment]
I'm actually interested in retargeting the library to support .NET Standard, so I have reopened the issue for now.

**Comment by RudeySH** [comment]
v1.0.12 is now available on NuGet and targets .NET Framework 4.5 and .NET Standard 2.1.
