### ISSUE TITLE
UpdateAll multiple colums

### ISSUE THREAD

**Issue by tiagossa1** [RudeySH/EntityFramework.Utilities#27]
Hello.
I'm trying to update multiple columns with your library, but how do I do that?

I've tried: `new { c.Col1, c.Col2 }`, but it doesn't seem to work... Any help?
Thanks.

**Comment by tiagossa1** [comment]
Not needed, found a way to do it.

**Comment by RudeySH** [comment]
I'm glad you figured it out. For future readers, here's the solution: Instead of `c => new { c.Col1, c.Col2 }`, do this: `c => c.Col1, c => c.Col2`.
